### ISSUE TITLE
是发生什么了吗

### ISSUE THREAD

**Issue by aiyi04** [OJZen/QMD_Android#35]
今天打开软件试图搜索结果加载了好久什么都没有  ，也尝试了之前搜索记录里能搜出来的歌。望恢复。

**Comment by OJZen** [comment]
更新1.7.2修复搜索空白

**Comment by aiyi04** [comment]
感谢解决！会继续支持的！！！

JZen ***@***.***> 于 2022年8月8日周一 11:09写道：
