### ISSUE TITLE
怎么获取qq音乐歌单的歌单码?!!!! QWQ!!??!

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [OJZen/QMD_Android#5]
我在用扫码器扫qq音乐分享歌单上的二维码时扫出来两个链接，第一个是直接扫出来的(`https://c.y.qq.com/base/fcgi-bin/u?__=7M3zy76`)第二个是扫出来后在浏览器访问中的地址(`https://i.y.qq.com/n2/m/share/details/taoge.html?ADTAG=erweimashare&appshare=android_qq&appversion=10110004&channelId=10036163&hosteuin=oK6kowEAoK4z7eSs7inANe-Poz%2A%2A&id=7412642123&openinqqmusic=1&platform=11`)

**Comment by OJZen** [comment]
如果你用浏览器打开这个地址，会跳转到```https://y.qq.com/n/yqq/playlist/7412642123.html```，那么歌单码就是```qmd:/7412642123```，复制到QMD添加即可。

**Comment by VernalsWind** [comment]
感谢，解决啦
