### ISSUE TITLE
歌名过长时错误

### ISSUE THREAD

**Issue by qadyuanzai** [OJZen/QMD_Android#7]
![Screenshot_20210722_170947_com huawei filemanager](https://user-images.githubusercontent.com/42380987/126615517-6454a574-642a-4953-8f60-51fb781d6ed2.jpg)
![Screenshot_20210722_171013_com tencent qqmusic](https://user-images.githubusercontent.com/42380987/126615527-27ab8d5e-80cc-4689-b60c-8a00f9b72877.jpg)
1、当歌名过长时下载的歌名会不全
2、由于歌名不全导致这几首歌下不了（这三首歌名在最后两个单词才有区别），下载时会提示已下载

**Comment by OJZen** [comment]
你去设置里面更改文件下载名，选择不带歌手名的。文件名长度是有限的。
